name: Daily Auto Commit

on:
  schedule:
    - cron: '30 2 * * *'   # 8:00 AM IST (Daily)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update auto file
        run: |
          echo "Updated on $(date -u)" >> auto

      - name: Commit changes
        run: |
          git config --global user.name "ANAND-JATOTHU"
          git config --global user.email "ANAND-JATOTHU@users.noreply.github.com"
          git add auto
          git commit -m "chore: daily auto commit" || echo "No changes to commit"

      - name: Push changes
        run: git push
